# swagger: '3.0'

# info:
#   version: 1.0.0
#   title: Form data API
#   description: Using form data body parameters

# paths:

#   /oauth/token:
#     post:
#       consumes:
#         - application/x-www-form-urlencoded
#       parameters:
#         - name: grant_type
#           type: string
#           in: formData
#         - name: client_id
#           type: string
#           in: formData
#         - name: client_secret
#           type: string
#           in: formData
#         - name: username
#           type: string
#           in: formData
#         - name: password
#           type: string
#           in: formData
#       responses:
#         200:
#           description: OK     
